apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: expense-project
 region: up-south-1

managedNodeGroups:
 - name: expense-project
   instanceType: m5.large
   desiredCapacity: 3
   spot: true

